services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP port for Neo4j Browser
      - "7687:7687" # Bolt port for Neo4j client connections
    env_file:
      - .env
    volumes:
      - neo4jdata:/data
    restart: unless-stopped

volumes:
  neo4jdata:
    name: neo4jdata
